name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    container:
      image: ramageek/image:php8.3-laravel-sonar

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment file
        run: cp .env.example .env

      - name: Setup SonarQube properties file
        run: cp sonar-project.properties.example sonar-project.properties

      - name: Test
        run: |
          ls -al
          which sonar-scanner
