name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    container:
      image: ramageek/image:php8.3-laravel-sonar

    steps:
      - uses: actions/checkout@v2

      - name: Setup application with code quality check
        run: |
          cp .env.example .env
          touch database/database.sqlite
          composer install --no-interaction --optimize-autoloader
          php artisan key:gen
          php artisan migrate --seed
          composer qc

      - name: Sonar scanning
        run: |
          cp sonar-project.properties.example sonar-project.properties
          sonar-scanner -Dsonar.login=$SONAR_LOGIN_TOKEN
