name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment file
        run: cp .env.example .env

      - name: Setup SonarQube properties file
        run: cp sonar-project.properties.example sonar-project.properties

      - name: Setup Application and Sonar Scanner
        env:
          SONAR_LOGIN_TOKEN: ${{ secrets.SONAR_LOGIN_TOKEN }}
        run: |
          docker run -it --rm ramageek/image:php8.3-laravel-sonar:latest bash -c "
            touch database/database.sqlite &&
            cp .env.example .env &&
            composer install --no-interaction --optimize-autoloader &&
            php artisan key:generate &&
            php artisan migrate --seed &&
            composer qc
            sonar-scanner
          "
